- hosts: vyos
  gather_facts: false
  connection: network_cli
  tasks:
   - name: Delete L3 interfaces
     vyos.vyos.vyos_l3_interfaces: &id001
       config:
         - name: eth2
         - name: eth1
       state: deleted
