- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: Parse commands to provide argspec
     vyos.vyos.vyos_l3_interfaces: &id001
       running_config: "{{ lookup('file', 'vyos_l3_interfaces.cfg') }}"
       state: parsed
