- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: Gather the interfaces from running config
     vyos.vyos.vyos_interfaces: &id001
       state: gathered
