- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
    - name: Merge the provided configuration with the existing running configuration for VyOS device
      register: result
      vyos_config:
        lines:
          - set interfaces ethernet eth1 description "demo do not save"
        save: true
