- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: ospfv3
     vyos.vyos.vyos_ospfv3: &id001
       config:
         - redistribute:
             - route_type: 'bgp'
           parameters:
             router_id: '10.10.10.10'
           ospf_area:
             - area: '0.0.0.0'
               range:
                 - address: '2001:db8:10::/64'
                 - address: '2001:db8:20::/64'
                 - address: '2001:db8:30::/64'
             - area: '2.2.2.2'
               range:
                 - address: '2001:db8:4::/64'
       state: replaced
