- hosts: iosxr-rdo
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.iosxr
  tasks: 
    - name: Delete provided configuration
      cisco.iosxr.iosxr_ospfv2: &id001
        config:
          processes:
            - process_id: 30
        state: deleted
