- hosts: iosxr-rdo
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.iosxr
  tasks: 
    - name: Gather provided configuration with device configuration
      cisco.iosxr.iosxr_ospfv2: &id001
        state: gathered
