- hosts: iosxr-rdo
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.iosxr
  tasks:
   - name: ospfv2
     cisco.iosxr.iosxr_ospfv2: &id001
       running_config: "{{ lookup('file', 'iosxr_ospfv2.cfg') }}"
       state: parsed
