- hosts: iosxr-rdo
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.iosxr
  tasks: 
    - name: Update provided configuration with device configuration
      cisco.iosxr.iosxr_ospfv2: &id001
        config:
          processes:
            - process_id: 27
              areas:
                - area_id: 10
                  hello_interval: 2
                  authentication:
                    keychain: 'ansi11393'
                - area_id: 30
                  dead_interval: 4
            - process_id: 26
              adjacency_stagger:
                min_adjacency: 11
                max_adjacency: 21
              authentication:
                message_digest:
                  keychain: 'ansible1101pass'
        state: merged
