- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
    - name: Setup
      vars:
        lines: "set service lldp\nset service lldp legacy-protocols 'cdp'\nset service\
          \ lldp management-address '192.0.2.17'\n"
      ansible.netcommon.cli_config:
        config: '{{ lines }}'
