- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: LLDP global resource module
     vyos.vyos.vyos_lldp_global: &id001
       config:
          address: 192.0.2.17
          enable: true
          legacy_protocols:
            - cdp
       state: rendered
