- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: ospfv2
     vyos.vyos.vyos_ospfv2: &id001
       config:
           areas:
             - area_id: '2'
               virtual_link:
                 - address: '1.1.1.1'
                   authentication:
                     md5:
                      - key_id: 1
                        md5_key: '05b7a99be72e3fe6'

                 - address: '1.1.1.2'
                 - address: '1.1.1.3'
                 - address: '1.1.1.4'
                   
       state: merged
