- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: l3_interfaces
     vyos.vyos.vyos_lag_interfaces: &id001
       config:
       state: deleted
