- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
    - name: Merge the provided configuration with the existing running configuration for VyOS device
      register: result
      vyos.vyos.vyos_lag_interfaces: &id001
        config:

          - name: bond0
            hash_policy: layer2
            mode: active-backup
            members:

              - member: eth1
            primary: eth1

          - name: bond1
            hash_policy: layer2+3
            mode: active-backup
            members:

              - member: eth2
            primary: eth2
        state: merged
