- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: ospfv2
     vyos.vyos.vyos_lag_interfaces: &id001
       running_config: "{{ lookup('file', 'vyos_lag_interfaces.cfg') }}"
       state: parsed
