- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: LAG interfaces resource module
     vyos.vyos.vyos_lag_interfaces: &id001
       config:
          - name: bond0
            hash_policy: layer2
            members:
              - member: eth1
            mode: active-backup
            primary: eth1
          - name: bond1
            hash_policy: layer2+3
            members:
              - member: eth2
            mode: active-backup
            primary: eth2
       state: rendered
