- hosts: iosxr
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.iosxr
  tasks:
   - name: ospfv2
     cisco.iosxr.iosxr_l2_interfaces: &id001
       running_config: "{{ lookup('file', 'iosxr_l2_interfaces.cfg') }}"
       state: parsed
