- hosts: iosxr
  connection: netconf

  tasks:
  - name: include yang role
    include_role:
      name: ansible-network.yang
      tasks_from: configure
    vars:
       yang_config_file: config/interfaces.json
       yang_model_name: openconfig-interfaces
       ansible_network_provider: cisco_iosxr
