- hosts: iosxr
  connection: netconf

  tasks:
   - name: get configuration/state data and convert to yang json format as per rfc 7951
     include_role:
       name: ansible-network.yang
       tasks_from: get
     vars:
       yang_get_filter: <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg"><interface-configuration></interface-configuration></interface-configurations>
       ansible_network_provider: cisco_iosxr
       yang_netconf_enable_task_run: false
       yang_get_output: ""
