- hosts: iosxr
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.cisco.iosxr
  tasks: 
    - name: Merge provided configuration with device configuration
      iosxr_interfaces: &id001
        config:
          - name: GigabitEthernet0/0/0/0
            description: Configured and Merged by Ansible-Network
            mtu: 110
            enabled: true
            duplex: half
          - name: GigabitEthernet0/0/0/1
            description: Configured and Merged by Ansible-Network
            mtu: 2800
            enabled: false
            speed: 100
            duplex: full
        state: merged
