- hosts: iosxr-rdo
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.iosxr
  tasks: 
    - name: Merge provided configuration with device configuration
      iosxr_interfaces: &id001
        config:
          - name: GigabitEthernet0/0/0/0
            description: Configured and Merged by Ansible-Network
          - name: GigabitEthernet0/0/0/1
            description: Configured and Merged by Ansible-Network
        state: merged
