- hosts: iosxr
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.iosxr
  tasks:
    - name: Populate Config
      vars:
        lines: "interface GigabitEthernet 0/0/0/0\ndescription this is interface0\n\
          mtu 65\nspeed 10\nno shutdown\ninterface GigabitEthernet 0/0/0/2\ndescription\
          \ this is interface1\nmtu 65\nspeed 10\nno shutdown\n"
      ansible.netcommon.cli_config:
        config: '{{ lines }}'
