- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: layer-2 interfaces
     vyos.vyos.vyos_lldp_interfaces: &id001
       config:
       state: gathered
