- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
    - name: Merge the provided configuration with the existing running configuration for VyOS device
      register: result
      vyos.vyos.vyos_lldp_interfaces: &id001
        config:

          - name: eth1
            location:
              civic_based:
                country_code: US
                ca_info:

                  - ca_type: 0
                    ca_value: ENGLISH

          - name: eth2
            location:
              coordinate_based:
                altitude: 2200
                datum: WGS84
                longitude: 222.267255W
                latitude: 33.524449N
        state: merged
