name: Greetings

on:
 - issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '@${{ github.actor }} Thank you for letting us know about this, we will get back to you whenever it will be possible.'
        pr-message: '@${{  github.actor }} Thank you for your contribution to ansi-book. We will get back to you whenever it will be possible.'
      
